<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="bunit" Version="1.27.17" />
    <PackageReference Include="bunit.web" Version="1.27.17" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.18" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.18" />
    <PackageReference Include="Moq.Contrib.HttpClient" Version="1.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Bunit" />
    <Using Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\July2025Capstone\July2025Capstone\July2025Capstone.csproj" />
    <ProjectReference Include="..\July2025Capstone\July2025Capstone.Client\July2025Capstone.Client.csproj" />
    <ProjectReference Include="..\July2025Capstone.shared\July2025Capstone.shared.csproj" />
    <ProjectReference Include="..\July2025Capstone\July2025Capstone\July2025Capstone.csproj" />
  </ItemGroup>

</Project>
