<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-July2025Capstone-118c192a-0fac-4513-80fd-4c988b261014</UserSecretsId>
    <!-- <UserSecretsId>dce50b63-d644-4f90-8871-e49733aca481</UserSecretsId> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2025.7.1" />
    <PackageReference Include="Syncfusion.Blazor" Version="30.2.7" />
    <ProjectReference Include="..\..\July2025Capstone.shared\July2025Capstone.Shared.csproj" />
    <ProjectReference Include="..\July2025Capstone.Client\July2025Capstone.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="8.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.18" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.18" />
  </ItemGroup>

</Project>
